blank_issues_enabled: true
contact_links:
  - name: Ask a How-To Question
    url:  https://stackoverflow.com/questions/tagged/lucene.net
    about: This issue tracker is for tracking the tasks to complete the port and improve the software. Please ask usability questions on StackOverflow. Always include BOTH the lucene.net tag and the lucene tag. Alternatively, join the Lucene.NET user mailing list by sending an email to user-subscribe@apache.org. Once signed up, you can submit your question to user@apache.org.
  - name: Join a Mailing List
    url:  https://lucenenet.apache.org/contributing/mailing-lists.html
    about: Join a Lucene.NET mailing list to ask user questions, discuss the design or other aspects of Lucene.NET with our team, or to track commits and builds. 
  - name: Issue with ICU4N
    url:  https://github.com/ICU4N/ICU4N/issues/new/choose
    about: Please open issues relating to International Components for Unicode for .NET (ICU4N) in ICU4N/ICU4N.
