blank_issues_enabled: true
contact_links:
  - name: Issue with J2N
    url:  https://github.com/NightOwl888/J2N/issues/new/choose
    about: Please open issues relating to J2N in NightOwl888/J2N.
  - name: Issue with ICU4N
    url:  https://github.com/ICU4N/ICU4N/issues/new/choose
    about: Please open issues relating to International Components for Unicode for .NET (ICU4N) in ICU4N/ICU4N.